apiVersion: v1
kind: ConfigMap
metadata:
  name: mongo-kubernetes-config
  labels:
     app: personservice
     version: "1.0.0"
data:
  mongodb_host: first-mongo-mongodb.personservice.svc.cluster.local
  mongodb_database: kubernetes-dummy
  authentication_database: admin
  mongodb_username: root