apiVersion: v1
kind: Namespace
metadata:
  annotations:
    yfactory-roles: "true"
  labels:
    accessLabel: echo-access-label
    env: "true"
    istio-injection: enabled
  name: personservice